const actionTypes ={
    
    //1 User
    GET_ONE_USER_SUCCESS :'GET_ONE_USER_SUCCESS',
    GET_ONE_USER_FAIL :'GET_ONE_USER_FAIL',
    //Users
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',

    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',

   
    GET_ALLUSER_SUCCESS: 'GET_ALLUSER_SUCCESS',
    GET_ALLUSER_FAIL: 'GET_ALLUSER_FAIL',
    

    GET_GENDER_SUCCESS :"GET_GENDER_SUCCESS",
    GET_ROLE_SUCCESS : "GET_ROLE_SUCCESS",


    //Admin
    GET_USER_ADMIN_SUCCESS :'GET_USER_ADMIN_SUCCESS',
    CREATE_USER_ADMIN_SUCCESS: 'CREATE_USER_ADMIN_SUCCESS',
    CREATE_USER_ADMIN_FAILED:"CREATE_USER_ADMIN_FAILED",
    DELETE_USER_ADMIN_SUCCESS: 'DELETE_USER_ADMIN_SUCCESS',
    UPDATE_USER_ADMIN_SUCCESS: 'UPDATE_USER_ADMIN_SUCCESS',
    GET_ALLUSER_ADMIN_SUCCESS: 'GET_ALLUSER_ADMIN_SUCCESS',
    LOGIN_USER_ADMIN_SUCCESS : 'LOGIN_USER_ADMIN_SUCCESS',
    
}

export default actionTypes;