const actionTypes ={
    
    //1 User
    GET_ONE_USER_SUCCESS :'GET_ONE_USER_SUCCESS',
    GET_ONE_USER_FAIL :'GET_ONE_USER_FAIL',
    //Users
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAIL: 'CREATE_USER_FAIL',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAIL: 'DELETE_USER_FAIL',

    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',
   
    GET_ALLUSER_SUCCESS: 'GET_ALLUSER_SUCCESS',
    GET_ALLUSER_FAIL: 'GET_ALLUSER_FAIL',

}

export default actionTypes;